/**
 * Country shapes grouped into franchise continents — the data behind the
 * Opportunities territory map. Generated from public/geo/world-countries.geo.json
 * + lib/worldPaths.ts; regenerate rather than hand-editing.
 *
 * Coordinates are in the same user space as `worldPaths` (viewBox 0 33 2000 800).
 * Antarctica, uninhabited islands and disputed areas are left out — they are
 * drawn as scenery, never offered as a territory.
 */

export type ContinentId = "af" | "as" | "eu" | "am" | "oc";

export type Territory = {
  /** ISO-3166 alpha-3 — the key into `worldPaths` */
  iso3: string;
  name: string;
  continent: ContinentId;
};

export const continents: {
  id: ContinentId;
  name: string;
  short: string;
  /** [x, y, w, h] of the region in map user space */
  box: [number, number, number, number];
}[] = [
  { id: "af", name: "Africa", short: "Africa", box: [902, 293, 382, 400] },
  { id: "as", name: "Asia & Middle East", short: "Asia", box: [1190, 192, 617, 366] },
  { id: "eu", name: "Europe", short: "Europe", box: [820, 60, 510, 320] },
  { id: "am", name: "Americas", short: "Americas", box: [46, 38, 761, 771] },
  { id: "oc", name: "Oceania", short: "Oceania", box: [1560, 500, 430, 290] },
];

/** Every country the map treats as a real market, alphabetical. */
export const territories: Territory[] = [
  { iso3: "AFG", name: "Afghanistan", continent: "as" },
  { iso3: "ALB", name: "Albania", continent: "eu" },
  { iso3: "DZA", name: "Algeria", continent: "af" },
  { iso3: "AGO", name: "Angola", continent: "af" },
  { iso3: "ARG", name: "Argentina", continent: "am" },
  { iso3: "ARM", name: "Armenia", continent: "eu" },
  { iso3: "AUS", name: "Australia", continent: "oc" },
  { iso3: "AUT", name: "Austria", continent: "eu" },
  { iso3: "AZE", name: "Azerbaijan", continent: "eu" },
  { iso3: "BHS", name: "Bahamas", continent: "am" },
  { iso3: "BGD", name: "Bangladesh", continent: "as" },
  { iso3: "BLR", name: "Belarus", continent: "eu" },
  { iso3: "BEL", name: "Belgium", continent: "eu" },
  { iso3: "BLZ", name: "Belize", continent: "am" },
  { iso3: "BEN", name: "Benin", continent: "af" },
  { iso3: "BMU", name: "Bermuda", continent: "am" },
  { iso3: "BTN", name: "Bhutan", continent: "as" },
  { iso3: "BOL", name: "Bolivia", continent: "am" },
  { iso3: "BIH", name: "Bosnia & Herzegovina", continent: "eu" },
  { iso3: "BWA", name: "Botswana", continent: "af" },
  { iso3: "BRA", name: "Brazil", continent: "am" },
  { iso3: "BRN", name: "Brunei", continent: "as" },
  { iso3: "BGR", name: "Bulgaria", continent: "eu" },
  { iso3: "BFA", name: "Burkina Faso", continent: "af" },
  { iso3: "BDI", name: "Burundi", continent: "af" },
  { iso3: "KHM", name: "Cambodia", continent: "as" },
  { iso3: "CMR", name: "Cameroon", continent: "af" },
  { iso3: "CAN", name: "Canada", continent: "am" },
  { iso3: "CAF", name: "Central African Republic", continent: "af" },
  { iso3: "TCD", name: "Chad", continent: "af" },
  { iso3: "CHL", name: "Chile", continent: "am" },
  { iso3: "CHN", name: "China", continent: "as" },
  { iso3: "COL", name: "Colombia", continent: "am" },
  { iso3: "COG", name: "Congo", continent: "af" },
  { iso3: "CRI", name: "Costa Rica", continent: "am" },
  { iso3: "HRV", name: "Croatia", continent: "eu" },
  { iso3: "CUB", name: "Cuba", continent: "am" },
  { iso3: "CYP", name: "Cyprus", continent: "eu" },
  { iso3: "CZE", name: "Czechia", continent: "eu" },
  { iso3: "DNK", name: "Denmark", continent: "eu" },
  { iso3: "DJI", name: "Djibouti", continent: "af" },
  { iso3: "DOM", name: "Dominican Republic", continent: "am" },
  { iso3: "COD", name: "DR Congo", continent: "af" },
  { iso3: "ECU", name: "Ecuador", continent: "am" },
  { iso3: "EGY", name: "Egypt", continent: "af" },
  { iso3: "SLV", name: "El Salvador", continent: "am" },
  { iso3: "GNQ", name: "Equatorial Guinea", continent: "af" },
  { iso3: "ERI", name: "Eritrea", continent: "af" },
  { iso3: "EST", name: "Estonia", continent: "eu" },
  { iso3: "SWZ", name: "Eswatini", continent: "af" },
  { iso3: "ETH", name: "Ethiopia", continent: "af" },
  { iso3: "FJI", name: "Fiji", continent: "oc" },
  { iso3: "FIN", name: "Finland", continent: "eu" },
  { iso3: "FRA", name: "France", continent: "eu" },
  { iso3: "GUF", name: "French Guiana", continent: "am" },
  { iso3: "GAB", name: "Gabon", continent: "af" },
  { iso3: "GMB", name: "Gambia", continent: "af" },
  { iso3: "GEO", name: "Georgia", continent: "eu" },
  { iso3: "DEU", name: "Germany", continent: "eu" },
  { iso3: "GHA", name: "Ghana", continent: "af" },
  { iso3: "GRC", name: "Greece", continent: "eu" },
  { iso3: "GTM", name: "Guatemala", continent: "am" },
  { iso3: "GIN", name: "Guinea", continent: "af" },
  { iso3: "GNB", name: "Guinea-Bissau", continent: "af" },
  { iso3: "GUY", name: "Guyana", continent: "am" },
  { iso3: "HTI", name: "Haiti", continent: "am" },
  { iso3: "HND", name: "Honduras", continent: "am" },
  { iso3: "HUN", name: "Hungary", continent: "eu" },
  { iso3: "ISL", name: "Iceland", continent: "eu" },
  { iso3: "IND", name: "India", continent: "as" },
  { iso3: "IDN", name: "Indonesia", continent: "as" },
  { iso3: "IRN", name: "Iran", continent: "as" },
  { iso3: "IRQ", name: "Iraq", continent: "as" },
  { iso3: "IRL", name: "Ireland", continent: "eu" },
  { iso3: "ISR", name: "Israel", continent: "as" },
  { iso3: "ITA", name: "Italy", continent: "eu" },
  { iso3: "CIV", name: "Ivory Coast", continent: "af" },
  { iso3: "JAM", name: "Jamaica", continent: "am" },
  { iso3: "JPN", name: "Japan", continent: "as" },
  { iso3: "JOR", name: "Jordan", continent: "as" },
  { iso3: "KAZ", name: "Kazakhstan", continent: "as" },
  { iso3: "KEN", name: "Kenya", continent: "af" },
  { iso3: "CS-KM", name: "Kosovo", continent: "eu" },
  { iso3: "KWT", name: "Kuwait", continent: "as" },
  { iso3: "KGZ", name: "Kyrgyzstan", continent: "as" },
  { iso3: "LAO", name: "Laos", continent: "as" },
  { iso3: "LVA", name: "Latvia", continent: "eu" },
  { iso3: "LBN", name: "Lebanon", continent: "as" },
  { iso3: "LSO", name: "Lesotho", continent: "af" },
  { iso3: "LBR", name: "Liberia", continent: "af" },
  { iso3: "LBY", name: "Libya", continent: "af" },
  { iso3: "LTU", name: "Lithuania", continent: "eu" },
  { iso3: "LUX", name: "Luxembourg", continent: "eu" },
  { iso3: "MDG", name: "Madagascar", continent: "af" },
  { iso3: "MWI", name: "Malawi", continent: "af" },
  { iso3: "MYS", name: "Malaysia", continent: "as" },
  { iso3: "MLI", name: "Mali", continent: "af" },
  { iso3: "MLT", name: "Malta", continent: "eu" },
  { iso3: "MRT", name: "Mauritania", continent: "af" },
  { iso3: "MEX", name: "Mexico", continent: "am" },
  { iso3: "MDA", name: "Moldova", continent: "eu" },
  { iso3: "MNG", name: "Mongolia", continent: "as" },
  { iso3: "MNE", name: "Montenegro", continent: "eu" },
  { iso3: "MAR", name: "Morocco", continent: "af" },
  { iso3: "MOZ", name: "Mozambique", continent: "af" },
  { iso3: "MMR", name: "Myanmar", continent: "as" },
  { iso3: "NAM", name: "Namibia", continent: "af" },
  { iso3: "NPL", name: "Nepal", continent: "as" },
  { iso3: "NLD", name: "Netherlands", continent: "eu" },
  { iso3: "NCL", name: "New Caledonia", continent: "oc" },
  { iso3: "NZL", name: "New Zealand", continent: "oc" },
  { iso3: "NIC", name: "Nicaragua", continent: "am" },
  { iso3: "NER", name: "Niger", continent: "af" },
  { iso3: "NGA", name: "Nigeria", continent: "af" },
  { iso3: "PRK", name: "North Korea", continent: "as" },
  { iso3: "MKD", name: "North Macedonia", continent: "eu" },
  { iso3: "NOR", name: "Norway", continent: "eu" },
  { iso3: "OMN", name: "Oman", continent: "as" },
  { iso3: "PAK", name: "Pakistan", continent: "as" },
  { iso3: "PAN", name: "Panama", continent: "am" },
  { iso3: "PNG", name: "Papua New Guinea", continent: "oc" },
  { iso3: "PRY", name: "Paraguay", continent: "am" },
  { iso3: "PER", name: "Peru", continent: "am" },
  { iso3: "PHL", name: "Philippines", continent: "as" },
  { iso3: "POL", name: "Poland", continent: "eu" },
  { iso3: "PRT", name: "Portugal", continent: "eu" },
  { iso3: "PRI", name: "Puerto Rico", continent: "am" },
  { iso3: "QAT", name: "Qatar", continent: "as" },
  { iso3: "ROU", name: "Romania", continent: "eu" },
  { iso3: "RUS", name: "Russia", continent: "eu" },
  { iso3: "RWA", name: "Rwanda", continent: "af" },
  { iso3: "SAU", name: "Saudi Arabia", continent: "as" },
  { iso3: "SEN", name: "Senegal", continent: "af" },
  { iso3: "SRB", name: "Serbia", continent: "eu" },
  { iso3: "SLE", name: "Sierra Leone", continent: "af" },
  { iso3: "SVK", name: "Slovakia", continent: "eu" },
  { iso3: "SVN", name: "Slovenia", continent: "eu" },
  { iso3: "SLB", name: "Solomon Islands", continent: "oc" },
  { iso3: "SOM", name: "Somalia", continent: "af" },
  { iso3: "ZAF", name: "South Africa", continent: "af" },
  { iso3: "KOR", name: "South Korea", continent: "as" },
  { iso3: "SSD", name: "South Sudan", continent: "af" },
  { iso3: "ESP", name: "Spain", continent: "eu" },
  { iso3: "LKA", name: "Sri Lanka", continent: "as" },
  { iso3: "SDN", name: "Sudan", continent: "af" },
  { iso3: "SUR", name: "Suriname", continent: "am" },
  { iso3: "SWE", name: "Sweden", continent: "eu" },
  { iso3: "CHE", name: "Switzerland", continent: "eu" },
  { iso3: "SYR", name: "Syria", continent: "as" },
  { iso3: "TWN", name: "Taiwan", continent: "as" },
  { iso3: "TJK", name: "Tajikistan", continent: "as" },
  { iso3: "TZA", name: "Tanzania", continent: "af" },
  { iso3: "THA", name: "Thailand", continent: "as" },
  { iso3: "TLS", name: "Timor-Leste", continent: "as" },
  { iso3: "TGO", name: "Togo", continent: "af" },
  { iso3: "TTO", name: "Trinidad & Tobago", continent: "am" },
  { iso3: "TUN", name: "Tunisia", continent: "af" },
  { iso3: "TUR", name: "Turkey", continent: "eu" },
  { iso3: "TKM", name: "Turkmenistan", continent: "as" },
  { iso3: "UGA", name: "Uganda", continent: "af" },
  { iso3: "UKR", name: "Ukraine", continent: "eu" },
  { iso3: "ARE", name: "United Arab Emirates", continent: "as" },
  { iso3: "GBR", name: "United Kingdom", continent: "eu" },
  { iso3: "USA", name: "United States", continent: "am" },
  { iso3: "URY", name: "Uruguay", continent: "am" },
  { iso3: "UZB", name: "Uzbekistan", continent: "as" },
  { iso3: "VUT", name: "Vanuatu", continent: "oc" },
  { iso3: "VEN", name: "Venezuela", continent: "am" },
  { iso3: "VNM", name: "Vietnam", continent: "as" },
  { iso3: "YEM", name: "Yemen", continent: "as" },
  { iso3: "ZMB", name: "Zambia", continent: "af" },
  { iso3: "ZWE", name: "Zimbabwe", continent: "af" },
];
